### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by DesTincT** [Agata-Lyod/music#10]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fmus.pieinthesky.ru%2F

<img width="337" alt="ivan sobolev_2018-12-14_15-48-30" src="https://user-images.githubusercontent.com/1612160/50002123-7feb6a00-ffb8-11e8-8a34-1ecc1d249e8a.png">
<img width="488" alt="ivan sobolev_2018-12-14_15-49-23" src="https://user-images.githubusercontent.com/1612160/50002124-7feb6a00-ffb8-11e8-9d48-5c2418cecca6.png">
<img width="629" alt="ivan sobolev_2018-12-14_15-50-08" src="https://user-images.githubusercontent.com/1612160/50002125-7feb6a00-ffb8-11e8-903e-07be950b2d5a.png">
<img width="298" alt="ivan sobolev_2018-12-14_15-51-08" src="https://user-images.githubusercontent.com/1612160/50002126-80840080-ffb8-11e8-8eac-fbb3b4a89270.png">
![Uploading ivan.sobolev_2018-12-14_15-51-47.png…]()

**Comment by Agata-Lyod** [comment]
Под валидатор подогнала
